# API base config
server.port=9006
server.servlet.context-path=/elearningapi

# Dev mail catcher (MailHog/Papercut)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# From et base URL frontend en dev
app.mail.from=Programme Leadership <no-reply@local.test>
app.frontend.base-url=http://localhost:3000

# Médias
app.media.video-directory=${VIDEO_DIRECTORY:D:/dimanche/iri/Api/videos}

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baselineOnMigrate=true

# JPA
spring.jpa.hibernate.ddl-auto=none

